### ISSUE TITLE
[Help] Why this pacakge require node version must be greater than v12

### ISSUE THREAD

**Issue by ChangeHow** [vanillaes/frontmeta#5]
env: Node v12.18

company production environment has locked node version in v12, but this package required node version must be greater than v14.

**Comment by evanplaice** [comment]
I got tired of Users complaining that I wasn't shipping 'Production Ready' software due to Node spitting out 'experimental' errors. Blame the Node.js maintainers for their poor experimental flagging strategy, they are already well aware of how I feel about it.

Why >14.x? Node v14.0 shipped with full ES module support and no obnoxious flags. Yes, 12.x works but making 14.x saves me from wasting any more time arguing about this.

My suggestion, when 14.x goes into LTS (Long Term Support) in a month see if your company can bump their environment minimum to 14.x. It has all of the ESM goodness plus TLA (top-level await) so it's worth it.

**Comment by ChangeHow** [comment]
Thank you for your answer, i couldn't agree your opinion anymore and I'm sorry to post that stupid question to you btw👍

**Comment by evanplaice** [comment]
No worries. It wasn't a stupid question, it was actually a very reasonable request. Sorry if I came off harsh.

I have just had bad experiences with the NodeJS community when it comes to modules. Many of the core NodeJS contributors working on the team implementing ES module support have been actively blocking the rollout for almost 3 years.

I know once 14x locked in to LTS there is no way they can further screw with ES module support so that's my target.
